[package]
name = "ffrostfall/bytenet"
version = "0.5.0"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"
exclude = [
	"dev",
	".eslintrc",
	".gitattributes",
	".gitignore",
	".prettierrc",
	"dev.project.json",
	"package.json",
	"mkdocs.yml",
	"stylua.toml",
	"tsconfig.json",
	"style.md",
	"CONTRIBUTING.md",
]
